### ISSUE TITLE
Printing functions missing from the manual

### ISSUE THREAD

**Issue by mortenpi** [JuliaCollections/AbstractTrees.jl#121]
E.g. `print_tree` and `printnode` do [have docstrings](https://github.com/JuliaCollections/AbstractTrees.jl/blob/master/src/printing.jl), but don't seem to show up anywhere in the manual. I presume they *are* considered part of the public API?

**Comment by FedeClaudi** [comment]
Just adding a +1 for this. I'm using `print_tree` in `Term.jl` (https://github.com/FedeClaudi/Term.jl/pull/187) and it took me a while to find/understand these functions.

**Comment by nhz2** [comment]
I assume that because `print_tree` is exported and is in the README, it is part of the public API. That would make #124 a breaking change, because `print_tree(f::Function, io::IO, tree; kwargs...)` no longer works. Could I add the `print_tree(f::Function, io::IO, tree; kwargs...)` method back? I think that would fix my package: https://github.com/medyan-dev/StorageTrees.jl/actions/runs/3896574335
