### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by timholy** [JuliaCollections/AbstractTrees.jl#69]
In the not too distant future I'll publish a blog post that requires #65. It would be good to get a new release before then. However, I've not paid close attention to developments here so I'll defer to @jlumpe about where we stand on that score.

**Comment by jlumpe** [comment]
Sorry, I've been really busy and haven't had the time to look at this. It seems like a good idea to release 0.3.4 since there have been several things fixed since 0.3.3.

I'm just now becoming familiar with the Julia package registry tools, my understanding of the process is:

* Submit and merge PR changing version in `Project.toml`
* Add comment on PR for Registrator
* After Registrator registers the new version, TagBot should tag the new release on GitHub

**Comment by timholy** [comment]
Yep, that's basically it. Slight modification: I don't think you can trigger the bot from a PR, I do it from https://github.com/JuliaCollections/AbstractTrees.jl/commits/master (at least, that's how it used to be, but I may be outdated).

Once you've gone through it a couple times it's about 1min of work. I typically edit the version number using the GitHub web interface. I submit the change as a PR only when I want feedback from others about whether we're ready for a new release or if I'm uncertain about what version number to use (e.g., is this a breaking release?). Otherwise I typically push the version-bump commits straight to master and immediately do a new release.

**Comment by jlumpe** [comment]
Thanks, done.
