### ISSUE TITLE
Add support `SortedTree` 

### ISSUE THREAD

**Issue by oscardssmith** [JuliaCollections/AbstractTrees.jl#97]
One of the main uses of trees is to maintain sorted invariants. As such, I think we should have a way of supporting the `find*` methods on trees that are O(depth) . I'm unsure of the best interface for this, so I would appreciate comments before I make a PR.
I think the best way to support this is with a trait
```
abstract type TreeOrdering end
struct NonOrderedTree<:TreeOrdering end
struct OrderedTree<:TreeOrdering end
TreeOrdering(::Type) = NonOrderedTree()
TreeOrdering(node) = TreeOrdering(typeof(node))
``` 
where `OrderedTree`s must implement `Base.isless` between any two nodes of the tree, and this order should respect the tree structure (i.e. the the children of a node are sorted, and the parent is less than all children) .

This should be enough to implement efficient methods for `findfirst` and the other find methods.

**Comment by oscardssmith** [comment]
One thing that makes doing this well hard is that some trees store data only in the leaves, and some store data in internal nodes as well

For an example of this being used
```
mutable struct TreeNode
   key::Int
   left::TreeNode
   right::TreeNode
   TreeNode() = new()
   TreeNode(x) = new(x)
   TreeNode(x,y,z) = new(x,y,z)
end
function tree(n=4)
    temp = rand(Int, n)
    root = TreeNode(temp[1])
    for i = 2:n
        insert(temp[i], root)
    end
    return root
end
function insert(key, n::TreeNode)
   if key < n.key
      if !isdefined(n,:left)
         n.left = TreeNode(key)
      else
         insert(key, n.left)
      end
   elseif key > n.key
      if !isdefined(n,:right)
         n.right = TreeNode(key)
      else
         insert(key, n.right)
      end
   end
end
function AbstractTrees.children(node::TreeNode)
    children = TreeNode[]
    if isdefined(node, :left)
        push!(children, node.left)
    end
    if isdefined(node, :right)
        push!(children, node.right)
    end
    children
end
AbstractTrees.nodevalue(node::TreeNode) = node.key
Base.isless(n1::TreeNode, n2::TreeNode) = Base.isless(n1.key, n2.key)
```

**Comment by ExpandingMan** [comment]
Your trait proposal sounds good to me, but I have some comments.
- I don't think you can use `isless` directly here, since the typing of the tree may be such that you want to return `true` for some check that doesn't make any sense in a more general context.  For example `0 < 1:3` returns a method error, but it might be useful in sorting the nodes of a tree (but I haven't worked out a full example, so maybe I'm imagining this wrongly).  You probably should provide a new function with reasonable defaults.
- I'd expect people would want to commonly use this on cases with node types that are not special e.g. numbers inside nested arrays.  This suggests that you want to be able to use this even for trees without the `OrderedTree()` trait.  One way to do this would be to eliminate the trait altogether, but perhaps that would be too dangerous.  Perhaps a better option is to just call `findsomething(OrderedTree(), non_special_tree)`.

**Comment by oscardssmith** [comment]
After a lot of thinking, I'm not sure that there is a generic version of this that will be generally useful.
